/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MySql_Windows_Forms_Project1
{
    public partial class frmMain : Form
    {
        public frmMain()
        {
            InitializeComponent();
        }


    private void frmanimalsToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmanimals f = new frmanimals();
      f.Show();
    }

    private void frmanimals1ToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmanimals1 f = new frmanimals1();
      f.Show();
    }

    private void frmpersonToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmperson f = new frmperson();
      f.Show();
    }

    private void frmshirtToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmshirt f = new frmshirt();
      f.Show();
    }

    }
}
