/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

namespace MySql_Windows_Forms_Project1
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.formsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmanimalsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmanimals1ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmpersonToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmshirtToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();

            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(284, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";

      this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { this.formsToolStripMenuItem });
      // 
      // formsToolStripMenuItem
      // 
      this.formsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { 
      this.frmanimalsToolStripMenuItem ,       this.frmanimals1ToolStripMenuItem ,       this.frmpersonToolStripMenuItem ,       this.frmshirtToolStripMenuItem       });
      this.formsToolStripMenuItem.Name = "formsToolStripMenuItem";
      this.formsToolStripMenuItem.Size = new System.Drawing.Size(52, 20);
      this.formsToolStripMenuItem.Text = "Forms"; 
      // 
      // frmanimalsToolStripMenuItem
      // 
      this.frmanimalsToolStripMenuItem.Name = "frmanimalsToolStripMenuItem";
      this.frmanimalsToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmanimalsToolStripMenuItem.Text = "animals";
      this.frmanimalsToolStripMenuItem.Click += new System.EventHandler(this.frmanimalsToolStripMenuItem_Click);
      // 
      // frmanimals1ToolStripMenuItem
      // 
      this.frmanimals1ToolStripMenuItem.Name = "frmanimals1ToolStripMenuItem";
      this.frmanimals1ToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmanimals1ToolStripMenuItem.Text = "animals1";
      this.frmanimals1ToolStripMenuItem.Click += new System.EventHandler(this.frmanimals1ToolStripMenuItem_Click);
      // 
      // frmpersonToolStripMenuItem
      // 
      this.frmpersonToolStripMenuItem.Name = "frmpersonToolStripMenuItem";
      this.frmpersonToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmpersonToolStripMenuItem.Text = "person";
      this.frmpersonToolStripMenuItem.Click += new System.EventHandler(this.frmpersonToolStripMenuItem_Click);
      // 
      // frmshirtToolStripMenuItem
      // 
      this.frmshirtToolStripMenuItem.Name = "frmshirtToolStripMenuItem";
      this.frmshirtToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmshirtToolStripMenuItem.Text = "shirt";
      this.frmshirtToolStripMenuItem.Click += new System.EventHandler(this.frmshirtToolStripMenuItem_Click);

            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 261);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "frmMain";
            this.Text = "Main Form";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem formsToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmanimalsToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmanimals1ToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmpersonToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmshirtToolStripMenuItem;

    }
}
