/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace MySql_Windows_Forms_Project1
{
	partial class frmshirt
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmshirt));
			this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
			this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
			this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
			this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
			this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
			this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
			
			this.Panel1 = new System.Windows.Forms.Panel();
			
			this.newDataSet = new NewDataSet();
			this.shirtBindingSource = new System.Windows.Forms.BindingSource(this.components);
			this.panel3 = new System.Windows.Forms.Panel();
			this.panel4 = new System.Windows.Forms.Panel();
			this.panel5 = new System.Windows.Forms.Panel();
			this.panel6 = new System.Windows.Forms.Panel();
			
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
			this.bindingNavigator1.SuspendLayout();
			this.panel3.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.newDataSet)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.shirtBindingSource)).BeginInit();
			
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// bindingNavigator1
			// 
			this.bindingNavigator1.AddNewItem = null;
			this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
			this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
			this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
			this.bindingNavigatorMoveFirstItem,
			this.bindingNavigatorMovePreviousItem,
			this.bindingNavigatorSeparator,
			this.bindingNavigatorPositionItem,
			this.bindingNavigatorCountItem,
			this.bindingNavigatorSeparator1,
			this.bindingNavigatorMoveNextItem,
			this.bindingNavigatorMoveLastItem,
			this.bindingNavigatorSeparator2,
			this.bindingNavigatorAddNewItem,
			this.bindingNavigatorDeleteItem,
			this.toolStripButton1});
			this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
			this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
			this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
			this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
			this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
			this.bindingNavigator1.Name = "bindingNavigator1";
			this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
			this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
			this.bindingNavigator1.Size = new System.Drawing.Size(360, 25);
			this.bindingNavigator1.TabIndex = 0;
			this.bindingNavigator1.Text = "bindingNavigator1";
			// 
			// bindingNavigatorAddNewItem
			// 
			this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
			this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
			this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorAddNewItem.Text = "Add new";
			this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
			// 
			// bindingNavigatorCountItem
			// 
			this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
			this.bindingNavigatorCountItem.Size = new System.Drawing.Size(35, 22);
			this.bindingNavigatorCountItem.Text = "of {0}";
			this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
			// 
			// bindingNavigatorDeleteItem
			// 
			this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
			this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
			this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorDeleteItem.Text = "Delete";
			// 
			// bindingNavigatorMoveFirstItem
			// 
			this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
			this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
			this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveFirstItem.Text = "Move first";
			// 
			// bindingNavigatorMovePreviousItem
			// 
			this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
			this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
			this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMovePreviousItem.Text = "Move previous";
			// 
			// bindingNavigatorSeparator
			// 
			this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
			this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorPositionItem
			// 
			this.bindingNavigatorPositionItem.AccessibleName = "Position";
			this.bindingNavigatorPositionItem.AutoSize = false;
			this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
			this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
			this.bindingNavigatorPositionItem.Text = "0";
			this.bindingNavigatorPositionItem.ToolTipText = "Current position";
			// 
			// bindingNavigatorSeparator1
			// 
			this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
			this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorMoveNextItem
			// 
			this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
			this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
			this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveNextItem.Text = "Move next";
			// 
			// bindingNavigatorMoveLastItem
			// 
			this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
			this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
			this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveLastItem.Text = "Move last";
			// 
			// bindingNavigatorSeparator2
			// 
			this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
			this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
			// 
			// toolStripButton1
			// 
			this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorSaveItem.Image")));
			this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
			this.toolStripButton1.Name = "toolStripButton1";
			this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
			this.toolStripButton1.Text = "Save";
			this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
			// 
			// errorProvider1
			// 
			this.errorProvider1.ContainerControl = this;
			//
			// Panel1
			//
			this.Panel1.AutoScroll = true;
			this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new System.Drawing.Point(0, 25);
			this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new System.Drawing.Size(656, 183);
			this.Panel1.TabIndex = 1;
			this.Panel1.AutoSize = true;
			
			this.bindingNavigator1.BindingSource = this.shirtBindingSource;
			// 
			// newDataSet
			// 
			this.newDataSet.DataSetName = "NewDataSet";
			this.newDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
			// 
			// tableBindingSource
			// 
			this.shirtBindingSource.DataMember = "shirt";
			this.shirtBindingSource.DataSource = this.newDataSet;
			//
			// idLabel
			//
			this.idLabel = new System.Windows.Forms.Label();
			this.idLabel.AutoSize = true;
			this.idLabel.Location = new System.Drawing.Point( 67, 50 );
			this.idLabel.Name = "idLabel";
			this.idLabel.Size = new System.Drawing.Size( 15, 13 );
			this.idLabel.TabIndex = 1;
			this.idLabel.Text = "id";
			this.Panel1.Controls.Add( this.idLabel );
			//
			// idTextBox
			//
			this.idTextBox = new System.Windows.Forms.TextBox();
			this.idTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.shirtBindingSource, "id", true ));
			this.idTextBox.Location = new System.Drawing.Point( 92, 50 );
			this.idTextBox.Name = "idTextBox";
			this.idTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.idTextBox.TabIndex = 2;
			this.idTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.idTextBox_Validating );
			this.Panel1.Controls.Add( this.idTextBox);
			//
			// stypeLabel
			//
			this.stypeLabel = new System.Windows.Forms.Label();
			this.stypeLabel.AutoSize = true;
			this.stypeLabel.Location = new System.Drawing.Point( 50, 76 );
			this.stypeLabel.Name = "stypeLabel";
			this.stypeLabel.Size = new System.Drawing.Size( 32, 13 );
			this.stypeLabel.TabIndex = 3;
			this.stypeLabel.Text = "stype";
			this.Panel1.Controls.Add( this.stypeLabel );
			//
			// stypeTextBox
			//
			this.stypeTextBox = new System.Windows.Forms.TextBox();
			this.stypeTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.shirtBindingSource, "stype", true ));
			this.stypeTextBox.Location = new System.Drawing.Point( 92, 76 );
			this.stypeTextBox.Name = "stypeTextBox";
			this.stypeTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.stypeTextBox.TabIndex = 4;
			this.stypeTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.stypeTextBox_Validating );
			this.Panel1.Controls.Add( this.stypeTextBox);
			//
			// colorLabel
			//
			this.colorLabel = new System.Windows.Forms.Label();
			this.colorLabel.AutoSize = true;
			this.colorLabel.Location = new System.Drawing.Point( 304, 50 );
			this.colorLabel.Name = "colorLabel";
			this.colorLabel.Size = new System.Drawing.Size( 30, 13 );
			this.colorLabel.TabIndex = 5;
			this.colorLabel.Text = "color";
			this.Panel1.Controls.Add( this.colorLabel );
			//
			// colorTextBox
			//
			this.colorTextBox = new System.Windows.Forms.TextBox();
			this.colorTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.shirtBindingSource, "color", true ));
			this.colorTextBox.Location = new System.Drawing.Point( 344, 50 );
			this.colorTextBox.Name = "colorTextBox";
			this.colorTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.colorTextBox.TabIndex = 6;
			this.colorTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.colorTextBox_Validating );
			this.Panel1.Controls.Add( this.colorTextBox);
			//
			// ownerLabel
			//
			this.ownerLabel = new System.Windows.Forms.Label();
			this.ownerLabel.AutoSize = true;
			this.ownerLabel.Location = new System.Drawing.Point( 298, 76 );
			this.ownerLabel.Name = "ownerLabel";
			this.ownerLabel.Size = new System.Drawing.Size( 36, 13 );
			this.ownerLabel.TabIndex = 7;
			this.ownerLabel.Text = "owner";
			this.Panel1.Controls.Add( this.ownerLabel );
			//
			// ownerTextBox
			//
			this.ownerTextBox = new System.Windows.Forms.TextBox();
			this.ownerTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.shirtBindingSource, "owner", true ));
			this.ownerTextBox.Location = new System.Drawing.Point( 344, 76 );
			this.ownerTextBox.Name = "ownerTextBox";
			this.ownerTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.ownerTextBox.TabIndex = 8;
			this.ownerTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.ownerTextBox_Validating );
			this.Panel1.Controls.Add( this.ownerTextBox);
			// 
			// panel4
			// 
			this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
			this.panel4.Location = new System.Drawing.Point(656, 0);
			this.panel4.Name = "panel4";
			this.panel4.Size = new System.Drawing.Size(10, 183);
			this.panel4.TabIndex = 3;
			// 
			// panel3
			// 
			this.panel3.Controls.Add(this.Panel1);
			this.panel3.Controls.Add(this.panel4);
			this.panel3.Controls.Add(this.panel5);
			this.panel3.Controls.Add(this.panel6);
			this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel3.Location = new System.Drawing.Point(0, 25);
			this.panel3.Name = "panel3";
			this.panel3.Size = new System.Drawing.Size(666, 183);
			this.panel3.TabIndex = 19;
			// 
			// panel5
			// 
			this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel5.Location = new System.Drawing.Point(0, 0);
			this.panel5.Name = "panel5";
			this.panel5.Size = new System.Drawing.Size(10, 183);
			this.panel5.TabIndex = 5;
			// 
			// panel6
			// 
			this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.panel6.Location = new System.Drawing.Point(0, 324);
			this.panel6.Name = "panel6";
			this.panel6.Size = new System.Drawing.Size(400, 10);
			this.panel6.TabIndex = 6;
			
			
			// 
			// frmshirt
			// 
			this.AutoScroll = true;
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(400, 359);
			this.Name = "frmshirt";
			this.Text = "frmshirt";
			this.Load += new System.EventHandler(this.frmshirt_Load);
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmshirt_FormClosing);
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
			this.bindingNavigator1.ResumeLayout(false);
			this.bindingNavigator1.PerformLayout();
			this.Text = "Shirt";
			((System.ComponentModel.ISupportInitialize)(this.newDataSet)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.shirtBindingSource)).EndInit();
			this.Controls.Add(this.panel3);
			this.panel3.ResumeLayout(false);
			this.panel3.PerformLayout();
			
			this.Controls.Add(this.bindingNavigator1);
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
			
		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private NewDataSet newDataSet;
		private System.Windows.Forms.BindingSource shirtBindingSource;
		private System.Windows.Forms.TextBox idTextBox;
		private System.Windows.Forms.Label idLabel;
		private System.Windows.Forms.TextBox stypeTextBox;
		private System.Windows.Forms.Label stypeLabel;
		private System.Windows.Forms.TextBox colorTextBox;
		private System.Windows.Forms.Label colorLabel;
		private System.Windows.Forms.TextBox ownerTextBox;
		private System.Windows.Forms.Label ownerLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

